sudo: false

language: erlang

notifications:
  email: false

otp_release:
  - 21.0
  - 20.3
  - 19.3

cache:
  directories:
  - "$HOME/.cache/rebar3"

script:
 - make eunit
 - make edoc
 - make xref
 - make dialyzer
 - make cover

